/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contents */
        get: operations["list_contents_v1_contents_get"];
        put?: never;
        /** Create Content */
        post: operations["create_content_v1_contents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Content */
        get: operations["read_content_v1_contents__content_id__get"];
        put?: never;
        post?: never;
        /** Delete Content */
        delete: operations["delete_content_v1_contents__content_id__delete"];
        options?: never;
        head?: never;
        /** Update Content */
        patch: operations["update_content_v1_contents__content_id__patch"];
        trace?: never;
    };
    "/v1/contents/{content_id}/assets/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Asset */
        post: operations["confirm_asset_v1_contents__content_id__assets_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents/{content_id}/assets/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Asset */
        post: operations["presign_asset_v1_contents__content_id__assets_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents/{content_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_v1_contents__content_id__snapshots_get"];
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_v1_contents__content_id__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents/{content_id}/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Snapshot */
        get: operations["read_snapshot_v1_contents__content_id__snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contents/{content_id}/snapshots/{snapshot_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Snapshot */
        post: operations["confirm_snapshot_v1_contents__content_id__snapshots__snapshot_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Generation */
        post: operations["create_demo_generation_v1_demo_generations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Session */
        post: operations["create_demo_session_v1_demo_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Demo Upload */
        post: operations["reject_demo_upload_v1_demo_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/demo/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Demo Workspace */
        get: operations["read_demo_workspace_v1_demo_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reject Demo Mutation */
        patch: operations["reject_demo_mutation_v1_demo_workspace_patch"];
        trace?: never;
    };
    "/v1/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Import Batch */
        get: operations["read_import_batch_v1_imports__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/imports/{batch_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_v1_imports__batch_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/imports/{batch_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Import Mapping */
        patch: operations["update_import_mapping_v1_imports__batch_id__mapping_patch"];
        trace?: never;
    };
    "/v1/imports/{batch_id}/rows/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Import Row */
        patch: operations["update_import_row_v1_imports__batch_id__rows__row_id__patch"];
        trace?: never;
    };
    "/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Current Session */
        delete: operations["delete_current_session_v1_sessions_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invite Session */
        post: operations["create_invite_session_v1_sessions_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_v1_workspaces__workspace_id__accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_v1_workspaces__workspace_id__accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_v1_workspaces__workspace_id__accounts__account_id__delete"];
        options?: never;
        head?: never;
        /** Update Account */
        patch: operations["update_account_v1_workspaces__workspace_id__accounts__account_id__patch"];
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}/columns-campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Column Campaigns */
        get: operations["list_column_campaigns_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns_get"];
        put?: never;
        /** Create Column Campaign */
        post: operations["create_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}/columns-campaigns/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Column Campaign */
        delete: operations["delete_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Column Campaign */
        patch: operations["update_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns__item_id__patch"];
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account Configuration */
        patch: operations["update_account_configuration_v1_workspaces__workspace_id__accounts__account_id__configuration_patch"];
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}/configuration/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Configuration Versions */
        get: operations["read_configuration_versions_v1_workspaces__workspace_id__accounts__account_id__configuration_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/accounts/{account_id}/effective-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Effective Configuration */
        get: operations["read_effective_configuration_v1_workspaces__workspace_id__accounts__account_id__effective_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/imports/manual/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Manual Import */
        post: operations["preview_manual_import_v1_workspaces__workspace_id__imports_manual_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/imports/screenshot/recognitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stage Screenshot Recognition */
        post: operations["stage_screenshot_recognition_v1_workspaces__workspace_id__imports_screenshot_recognitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/imports/tabular/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Tabular Import */
        post: operations["preview_tabular_import_v1_workspaces__workspace_id__imports_tabular_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members/codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Member Code */
        post: operations["create_member_code_v1_workspaces__workspace_id__members_codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspace_id}/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_v1_workspaces__workspace_id__members__member_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /** Benchmark Sample Size */
            benchmark_sample_size: number;
            /** Metric Weights */
            metric_weights: {
                [key: string]: number;
            };
            /** Name */
            name: string;
            /** Objectives */
            objectives: string[];
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
        };
        /** AccountRead */
        AccountRead: {
            benchmark_profile: components["schemas"]["BenchmarkProfileRead"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            objective_profile: components["schemas"]["ObjectiveProfileRead"];
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** AccountSummaryRead */
        AccountSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** AccountUpdate */
        AccountUpdate: {
            /** Name */
            name: string;
        };
        /** AssetConfirmRequest */
        AssetConfirmRequest: {
            /** Upload Token */
            upload_token: string;
        };
        /** AssetPresignRequest */
        AssetPresignRequest: {
            /**
             * Category
             * @enum {string}
             */
            category: "cover" | "screenshot" | "reference_image" | "document";
            /** File Name */
            file_name: string;
            /**
             * Mime Type
             * @enum {string}
             */
            mime_type: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "application/vnd.openxmlformats-officedocument.wordprocessingml.document" | "text/plain";
            /** Size */
            size: number;
        };
        /** AssetRead */
        AssetRead: {
            /**
             * Category
             * @enum {string}
             */
            category: "cover" | "screenshot" | "reference_image" | "document";
            /** Download Url */
            download_url?: string | null;
            /** Download Url Expires At */
            download_url_expires_at?: string | null;
            /** File Name */
            file_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime Type */
            mime_type: string;
            /** Size */
            size: number;
        };
        /** AssetUploadGrantRead */
        AssetUploadGrantRead: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Object Key */
            object_key: string;
            /** Upload Headers */
            upload_headers: {
                [key: string]: string;
            };
            /** Upload Token */
            upload_token: string;
            /** Upload Url */
            upload_url: string;
        };
        /** BenchmarkProfileRead */
        BenchmarkProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sample Size */
            sample_size: number;
            /** Version */
            version: number;
        };
        /** Body_preview_tabular_import_v1_workspaces__workspace_id__imports_tabular_preview_post */
        Body_preview_tabular_import_v1_workspaces__workspace_id__imports_tabular_preview_post: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            content_type: components["schemas"]["ContentType"];
            /** File */
            file: string;
            platform: components["schemas"]["Platform"];
        };
        /** Body_stage_screenshot_recognition_v1_workspaces__workspace_id__imports_screenshot_recognitions_post */
        Body_stage_screenshot_recognition_v1_workspaces__workspace_id__imports_screenshot_recognitions_post: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Body */
            body: string;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            content_type: components["schemas"]["ContentType"];
            /** File */
            file: string;
            platform: components["schemas"]["Platform"];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Retention Policy */
            retention_policy: string;
            /** Title */
            title: string;
        };
        /** ColumnCampaignCreate */
        ColumnCampaignCreate: {
            /** Benchmark Sample Size */
            benchmark_sample_size?: number | null;
            /** Ends At */
            ends_at?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "column" | "campaign";
            /** Metric Weights */
            metric_weights?: {
                [key: string]: number;
            } | null;
            /** Name */
            name: string;
            /** Objectives */
            objectives?: string[] | null;
            /** Starts At */
            starts_at?: string | null;
        };
        /** ColumnCampaignRead */
        ColumnCampaignRead: {
            /** Benchmark Profile Id */
            benchmark_profile_id: string | null;
            /** Ends At */
            ends_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "column" | "campaign";
            /** Name */
            name: string;
            /** Objective Profile Id */
            objective_profile_id: string | null;
            /** Starts At */
            starts_at: string | null;
        };
        /** ColumnCampaignUpdate */
        ColumnCampaignUpdate: {
            /**
             * Restore Account Defaults
             * @constant
             */
            restore_account_defaults: true;
        };
        /** ConfigurationInput */
        ConfigurationInput: {
            /** Benchmark Sample Size */
            benchmark_sample_size: number;
            /** Metric Weights */
            metric_weights: {
                [key: string]: number;
            };
            /** Objectives */
            objectives: string[];
        };
        /** ConfigurationVersionsRead */
        ConfigurationVersionsRead: {
            /** Benchmarks */
            benchmarks: components["schemas"]["BenchmarkProfileRead"][];
            /** Objectives */
            objectives: components["schemas"]["ObjectiveProfileRead"][];
        };
        /** ContentCreate */
        ContentCreate: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Body */
            body: string;
            /** Column Campaign Id */
            column_campaign_id?: string | null;
            /**
             * Content Type
             * @default video
             * @enum {string}
             */
            content_type: "video" | "image_text";
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /** Platform Content Id */
            platform_content_id?: string | null;
            /** Title */
            title: string;
            /** Work Url */
            work_url?: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ContentRead */
        ContentRead: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Account Name */
            account_name: string;
            /** Assets */
            assets: components["schemas"]["AssetRead"][];
            /**
             * Benchmark Profile Id
             * Format: uuid
             */
            benchmark_profile_id: string;
            /** Body */
            body: string;
            /** Column Campaign Id */
            column_campaign_id: string | null;
            /** Column Campaign Name */
            column_campaign_name: string | null;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "image_text";
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Objective Profile Id
             * Format: uuid
             */
            objective_profile_id: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /** Platform Content Id */
            platform_content_id: string | null;
            /** Published At */
            published_at: string | null;
            /** Published Body */
            published_body: string | null;
            /** Published Title */
            published_title: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Title */
            title: string;
            /** Work Url */
            work_url: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /**
         * ContentType
         * @enum {string}
         */
        ContentType: "video" | "image_text";
        /** ContentUpdate */
        ContentUpdate: {
            /** Body */
            body?: string | null;
            /** Column Campaign Id */
            column_campaign_id?: string | null;
            /** Restore */
            restore?: true | null;
            /** Status */
            status?: ("published" | "archived") | null;
            /** Title */
            title?: string | null;
            /** Work Url */
            work_url?: string | null;
        };
        /** DemoAccountRead */
        DemoAccountRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /** Posts */
            posts: components["schemas"]["DemoPostRead"][];
            /** Synthetic */
            synthetic: boolean;
        };
        /** DemoGenerateRequest */
        DemoGenerateRequest: {
            /** Prompt */
            prompt: string;
        };
        /** DemoGenerateResponse */
        DemoGenerateResponse: {
            /** Content */
            content: string;
            /** Ip Remaining */
            ip_remaining: number;
            /**
             * Label
             * @default Mock 输出
             */
            label: string;
            /**
             * Mock
             * @default true
             */
            mock: boolean;
            /** Session Remaining */
            session_remaining: number;
        };
        /** DemoPostMetrics */
        DemoPostMetrics: {
            /** Comments */
            comments: number;
            /** Likes */
            likes: number;
            /** Views */
            views: number;
        };
        /** DemoPostRead */
        DemoPostRead: {
            /** Id */
            id: string;
            metrics: components["schemas"]["DemoPostMetrics"];
            /** Published At */
            published_at: string;
            /** Synthetic */
            synthetic: boolean;
            /** Title */
            title: string;
        };
        /** DemoSessionCreated */
        DemoSessionCreated: {
            /** Generation Limit */
            generation_limit: number;
        };
        /** DemoWorkspaceRead */
        DemoWorkspaceRead: {
            /** Accounts */
            accounts: components["schemas"]["DemoAccountRead"][];
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** EffectiveConfigurationRead */
        EffectiveConfigurationRead: {
            benchmark_profile: components["schemas"]["BenchmarkProfileRead"];
            objective_profile: components["schemas"]["ObjectiveProfileRead"];
            /**
             * Source
             * @enum {string}
             */
            source: "account_default" | "column_override" | "campaign_override";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeaderMappingRead */
        HeaderMappingRead: {
            /** Confidence */
            confidence: number;
            /** High Confidence */
            high_confidence: boolean;
            /** Source Header */
            source_header: string;
            /** Target Field */
            target_field: string | null;
        };
        /** HeaderMappingUpdate */
        HeaderMappingUpdate: {
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
        };
        /** ImportBatchRead */
        ImportBatchRead: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "image_text";
            /** File Name */
            file_name: string | null;
            /** Header Mappings */
            header_mappings: components["schemas"]["HeaderMappingRead"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /** Recognition Error */
            recognition_error: string | null;
            /** Recognition Status */
            recognition_status: ("pending" | "processing" | "ready" | "failed") | null;
            /** Rows */
            rows: components["schemas"]["ImportRowRead"][];
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "manual" | "csv" | "xlsx" | "screenshot";
            /**
             * Status
             * @enum {string}
             */
            status: "preview" | "confirmed";
            summary: components["schemas"]["ImportSummaryRead"];
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ImportConfirmRequest */
        ImportConfirmRequest: {
            /** Selected Row Ids */
            selected_row_ids: string[];
        };
        /** ImportConfirmationRead */
        ImportConfirmationRead: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Content Ids */
            content_ids: string[];
            /** Skipped Row Ids */
            skipped_row_ids: string[];
            /** Snapshot Ids */
            snapshot_ids: string[];
        };
        /** ImportErrorRead */
        ImportErrorRead: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** ImportRowRead */
        ImportRowRead: {
            /** Dedupe Reason */
            dedupe_reason: string | null;
            /** Errors */
            errors: components["schemas"]["ImportErrorRead"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Content Id */
            matched_content_id: string | null;
            /** Normalized Data */
            normalized_data: {
                [key: string]: unknown;
            };
            /** Raw Data */
            raw_data: {
                [key: string]: unknown;
            };
            /** Row Number */
            row_number: number;
            /** Selected */
            selected: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "update" | "suspected_duplicate" | "failed";
        };
        /** ImportRowUpdate */
        ImportRowUpdate: {
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Selected */
            selected?: boolean | null;
        };
        /** ImportSummaryRead */
        ImportSummaryRead: {
            /** Failed */
            failed: number;
            /** New */
            new: number;
            /** Suspected Duplicate */
            suspected_duplicate: number;
            /** Update */
            update: number;
        };
        /** InviteLogin */
        InviteLogin: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
        };
        /** ManualPreviewRequest */
        ManualPreviewRequest: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "image_text";
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** MemberCodeCreate */
        MemberCodeCreate: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "editor" | "viewer";
        };
        /** MemberCodeCreated */
        MemberCodeCreated: {
            /** Code */
            code: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "editor" | "viewer";
        };
        /** ObjectiveProfileRead */
        ObjectiveProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metric Weights */
            metric_weights: {
                [key: string]: number;
            };
            /** Objectives */
            objectives: string[];
            /** Version */
            version: number;
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "douyin" | "xiaohongshu";
        /** SessionCreated */
        SessionCreated: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * Member Id
             * Format: uuid
             */
            member_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** SnapshotCompletenessRead */
        SnapshotCompletenessRead: {
            /** Missing */
            missing: ("1h" | "24h" | "72h" | "7d")[];
            /** Observed */
            observed: ("1h" | "24h" | "72h" | "7d")[];
            /** Ratio */
            ratio: number;
        };
        /** SnapshotCreate */
        SnapshotCreate: {
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Metrics */
            metrics: components["schemas"]["SnapshotMetricInput"][];
            /** Original Screenshot Asset Id */
            original_screenshot_asset_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "tabular_import" | "screenshot" | "extension";
        };
        /** SnapshotMetricInput */
        SnapshotMetricInput: {
            /** Key */
            key: string;
            /** Ocr Confidence */
            ocr_confidence?: number | null;
            /** Raw Value */
            raw_value: number | string | null;
        };
        /** SnapshotMetricRead */
        SnapshotMetricRead: {
            /** Eligible For Benchmark */
            eligible_for_benchmark: boolean;
            /** Key */
            key: string;
            /** Normalized Value */
            normalized_value: string | null;
            /** Ocr Confidence */
            ocr_confidence: number | null;
            /** Raw Value */
            raw_value: string | null;
        };
        /** SnapshotRead */
        SnapshotRead: {
            /** Age Seconds */
            age_seconds: number;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            completeness: components["schemas"]["SnapshotCompletenessRead"];
            /** Confirmed */
            confirmed: boolean;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Content Id
             * Format: uuid
             */
            content_id: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "video" | "image_text";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Maturity Bucket
             * @enum {string}
             */
            maturity_bucket: "1h" | "24h" | "72h" | "7d";
            /** Metrics */
            metrics: components["schemas"]["SnapshotMetricRead"][];
            /** Original Screenshot Asset Id */
            original_screenshot_asset_id: string | null;
            /**
             * Platform
             * @enum {string}
             */
            platform: "douyin" | "xiaohongshu";
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "tabular_import" | "screenshot" | "extension";
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /** WorkspaceCreated */
        WorkspaceCreated: {
            /** Admin Code */
            admin_code: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** WorkspaceMemberRead */
        WorkspaceMemberRead: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "editor" | "viewer" | "demo";
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** WorkspaceMemberUpdate */
        WorkspaceMemberUpdate: {
            /** Revoked */
            revoked?: true | null;
            /** Role */
            role?: ("admin" | "editor" | "viewer") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_contents_v1_contents_get: {
        parameters: {
            query: {
                workspace_id: string;
                trash?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_content_v1_contents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_content_v1_contents__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_content_v1_contents__content_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_content_v1_contents__content_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_asset_v1_contents__content_id__assets_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_asset_v1_contents__content_id__assets_presign_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetPresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetUploadGrantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_v1_contents__content_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_v1_contents__content_id__snapshots_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_snapshot_v1_contents__content_id__snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_id: string;
                snapshot_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_snapshot_v1_contents__content_id__snapshots__snapshot_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                content_id: string;
                snapshot_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_generation_v1_demo_generations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                demo_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_session_v1_demo_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSessionCreated"];
                };
            };
        };
    };
    reject_demo_upload_v1_demo_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_demo_workspace_v1_demo_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoWorkspaceRead"];
                };
            };
        };
    };
    reject_demo_mutation_v1_demo_workspace_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_import_batch_v1_imports__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_v1_imports__batch_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                batch_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportConfirmationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_import_mapping_v1_imports__batch_id__mapping_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                batch_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeaderMappingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_import_row_v1_imports__batch_id__rows__row_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                batch_id: string;
                row_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_current_session_v1_sessions_current_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_session_v1_sessions_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_v1_workspaces__workspace_id__accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_v1_workspaces__workspace_id__accounts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_v1_workspaces__workspace_id__accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_v1_workspaces__workspace_id__accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_column_campaigns_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnCampaignRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnCampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnCampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
                item_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_column_campaign_v1_workspaces__workspace_id__accounts__account_id__columns_campaigns__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
                item_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnCampaignUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnCampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_account_configuration_v1_workspaces__workspace_id__accounts__account_id__configuration_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_configuration_versions_v1_workspaces__workspace_id__accounts__account_id__configuration_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigurationVersionsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_effective_configuration_v1_workspaces__workspace_id__accounts__account_id__effective_configuration_get: {
        parameters: {
            query?: {
                column_campaign_id?: string | null;
                at?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
                account_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveConfigurationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_manual_import_v1_workspaces__workspace_id__imports_manual_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stage_screenshot_recognition_v1_workspaces__workspace_id__imports_screenshot_recognitions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_stage_screenshot_recognition_v1_workspaces__workspace_id__imports_screenshot_recognitions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_tabular_import_v1_workspaces__workspace_id__imports_tabular_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_tabular_import_v1_workspaces__workspace_id__imports_tabular_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_member_code_v1_workspaces__workspace_id__members_codes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberCodeCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_v1_workspaces__workspace_id__members__member_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                member_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceMemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceMemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
